site:
  title: Skupper 
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://skupper.io
  start_page: skupper::index.adoc
content:
  sources:
  - url: ../skupper-docs
    branches: HEAD
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    edit_url: false
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    context: rhsi
    linkroot: link
    service-network: service network
    image-prefix: images
    skupper-version: 1.4.2
    skupperoperatorname: Skupper Operator
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
